### ISSUE TITLE
About showing images

### ISSUE THREAD

**Issue by mbeytekin** [brandonschmeidler/imgui-gamemaker#1]
Hello. I've been dealing with the extension for a while and its performance is very good. But I guess you didn't touch the image display parts. I thought I could do this with IMGUI's add image functions, but I couldn't figure out how to add it to DLL source code. Actually, after sending a surface from GM to the buffer, I send this buffer starting address to C ++. Do you have any suggestions to show the image in this buffer in IMGUI's draw functions? Thanks in advance.

MBeytekin

**Comment by noiamhippyman** [comment]
Unfortunately this was actually the thing that I stopped at because I couldn't figure out how to make it work. If you can figure it out I'd love it if you'd be willing to share how you did it.

**Comment by mbeytekin** [comment]
Yes, the IMGUI texture system is a bit complicated. But I have an idea. If I can create a plane-shaped vertex buffer in GameMaker and convert it to ID3D11ShaderResourceView format, which IMGUI accepts as texture, then it will be solved. So creating a texture and ID3D11ShaderResourceView again in C ++ does not seem like a good idea to me in terms of performance. If ID3D11ShaderResourceView is created in GM, when we simply load it into a buffer and send it to the dll, it will already be in IMGUI's texture format. It is also an idea to use D3DX11CreateShaderResourceViewFromMemory in DLL. I'm dealing with this right now. If there is an improvement, I will write.

**Comment by noiamhippyman** [comment]
Thanks for taking a stab at it! I'd love to get a fully functioning ImGui implementation with docking/viewports. That's the only reason I started this instead of using ImGuiGML made by another member of the GMC.

**Comment by mbeytekin** [comment]
Actually i am currently using imguigml in one of my application. (https://store.steampowered.com/app/1516050/Pixel_Art_Workshop/) but after user feedback I noticed that IMGUIGML is using excessive CPU. 20-25% even in idle. So I went on a different quest for different GUI and found your work. I liked your logic very much. and very fast according to IMGUIGML. If you have time I would like to help you improve this. There are some things I have been able to do so far, but there was a point I couldn't solve. I have somehow managed to upload and show a picture in the video in the attachment, but the host shows the screen of the program as if it were receiving a wrong pointer.

https://user-images.githubusercontent.com/76127603/115105511-1acd2800-9f68-11eb-9ba6-41d45c8a9a40.mp4

I did it with ;
https://github.com/ocornut/imgui/wiki/Image-Loading-and-Displaying-Examples

The functions I add are;

            `bool CreateDeviceD3D(HWND hWnd)
            {
	            // Setup swap chain
	            DXGI_SWAP_CHAIN_DESC sd;
	            ZeroMemory(&sd, sizeof(sd));
	            sd.BufferCount = 2;
	            sd.BufferDesc.Width = 0;
	            sd.BufferDesc.Height = 0;
	            sd.BufferDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
	            sd.BufferDesc.RefreshRate.Numerator = 60;
	            sd.BufferDesc.RefreshRate.Denominator = 1;
	            sd.Flags = DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH;
	            sd.BufferUsage = DXGI_USAGE_RENDER_TARGET_OUTPUT;
	            sd.OutputWindow = hWnd;
	            sd.SampleDesc.Count = 1;
	            sd.SampleDesc.Quality = 0;
	            sd.Windowed = TRUE;
	            sd.SwapEffect = DXGI_SWAP_EFFECT_DISCARD; 
	            
	            UINT createDeviceFlags = 0;
	            //createDeviceFlags |= D3D11_CREATE_DEVICE_DEBUG;
	            D3D_FEATURE_LEVEL featureLevel;
	            const D3D_FEATURE_LEVEL featureLevelArray[2] = { D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_10_0, };
	            if (D3D11CreateDeviceAndSwapChain(NULL, D3D_DRIVER_TYPE_HARDWARE, NULL, createDeviceFlags, featureLevelArray, 2, D3D11_SDK_VERSION, &sd, &g_pSwapChain, &g_pd3dDevice, &featureLevel, &g_pd3dDeviceContext) != S_OK)
		            return false;
            
	            CreateRenderTarget();
	            return true;
            }
            
            void CleanupDeviceD3D()
            {
	            CleanupRenderTarget();
	            if (g_pSwapChain) { g_pSwapChain->Release(); g_pSwapChain = NULL; }
	            if (g_pd3dDeviceContext) { g_pd3dDeviceContext->Release(); g_pd3dDeviceContext = NULL; }
	            if (g_pd3dDevice) { g_pd3dDevice->Release(); g_pd3dDevice = NULL; }
            }
            
            void CreateRenderTarget()
            {
	            ID3D11Texture2D* pBackBuffer;
	            g_pSwapChain->GetBuffer(0, IID_PPV_ARGS(&pBackBuffer));
	            g_pd3dDevice->CreateRenderTargetView(pBackBuffer, NULL, &g_mainRenderTargetView);
	            pBackBuffer->Release();
            }
            
            void CleanupRenderTarget()
            {
	            if (g_mainRenderTargetView) { g_mainRenderTargetView->Release(); g_mainRenderTargetView = NULL; }
            }`


for loading a texture to memory

            `ID3D11ShaderResourceView* my_texture = nullptr;
            int my_image_width = 0;
            int my_image_height = 0;
            fn_export double imgui_showimage() {
            
            
	            
            
	            bool ret = LoadTextureFromFile("e:\\mario1_input.png", &my_texture, &my_image_width, &my_image_height);
	            //IM_ASSERT(ret);
	            
	            return 1;
	            `

to show the texture in memory;

            `fn_export double imgui_showtextureinmemory() {
	            ImGui::Text("pointer = %p", my_texture);
	            ImGui::Text("size = %d x %d", my_image_width, my_image_height);
	            ImGui::Image((void*)my_texture, ImVec2(my_image_width, my_image_height));
	            
	            return 1;
            }`

this part copied from Display Samples page;

                `bool LoadTextureFromFile(const char* filename, ID3D11ShaderResourceView** out_srv, int* out_width, int* out_height)
                {
	                // Load from disk into a raw RGBA buffer
	                int image_width = 0;
	                int image_height = 0;
	                unsigned char* image_data = stbi_load(filename, &image_width, &image_height, NULL, 4);
	                if (image_data == NULL)
		                return false;
                
	                //HWND hw = GetActiveWindow();
	                //CreateDeviceD3D(hw);
                
	                // Create texture
	                D3D11_TEXTURE2D_DESC desc;
	                ZeroMemory(&desc, sizeof(desc));
	                desc.Width = image_width;
	                desc.Height = image_height;
	                desc.MipLevels = 1;
	                desc.ArraySize = 1;
	                desc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
	                desc.SampleDesc.Count = 1;
	                desc.Usage = D3D11_USAGE_DEFAULT;
	                desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
	                desc.CPUAccessFlags = 0;
                
	                ID3D11Texture2D *pTexture = NULL;
	                D3D11_SUBRESOURCE_DATA subResource;
	                subResource.pSysMem = image_data;
	                subResource.SysMemPitch = desc.Width * 4;
	                subResource.SysMemSlicePitch = 0;
	                g_pd3dDevice->CreateTexture2D(&desc, &subResource, &pTexture);
                
	                // Create texture view
	                D3D11_SHADER_RESOURCE_VIEW_DESC srvDesc;
	                ZeroMemory(&srvDesc, sizeof(srvDesc));
	                srvDesc.Format = DXGI_FORMAT_R8G8B8A8_UNORM;
	                srvDesc.ViewDimension = D3D11_SRV_DIMENSION_TEXTURE2D;
	                srvDesc.Texture2D.MipLevels = desc.MipLevels;
	                srvDesc.Texture2D.MostDetailedMip = 0;
	                g_pd3dDevice->CreateShaderResourceView(pTexture, &srvDesc, out_srv);
	                pTexture->Release();
                
	                *out_width = image_width;
	                *out_height = image_height;
	                stbi_image_free(image_data);
                
	                return true;
                }`

it works but with corrupted texture as above..

Maybe you have an idea about this..

**Comment by mbeytekin** [comment]
In fact, I think I can send a texture in GM directly to the DLL using OpenGL backend. I'm trying it now. If I can do that anyway, everything will be solved.

**Comment by mbeytekin** [comment]
Hi again, I tried it with opengl backend and was able to show it in imgui by taking the image directly from a surface with buffer_get_address (surfacebuffer).

My intention is actually to copy constantly used static images (such as Toolbar images) into memory beforehand and refresh only dynamic images. So the code runs pretty fast.
At this stage, we have two options:
1) Convert your codes to opengl backend if you have time.
2) To be able to accomplish in DirectX11 what I did with OpenGL.

What do you think?

If you can help with this, this extension you wrote will be very useful for many people.

![resim](https://user-images.githubusercontent.com/76127603/115113196-cfc80a80-9f91-11eb-8cb2-6d1c0a8af246.png)

![resim](https://user-images.githubusercontent.com/76127603/115113208-e5d5cb00-9f91-11eb-9ec2-2257018fc487.png)

![resim](https://user-images.githubusercontent.com/76127603/115113240-02720300-9f92-11eb-8d0b-d563bcd8f930.png)

![resim](https://user-images.githubusercontent.com/76127603/115113275-31887480-9f92-11eb-92f1-fcbd1c840904.png)

![resim](https://user-images.githubusercontent.com/76127603/115113339-790f0080-9f92-11eb-944c-79dec9dcc58e.png)

**Comment by noiamhippyman** [comment]
I apologize for the crazy long hiatus. I needed a break from programming. Took up woodworking and it's been fun. But I'm back to messing around with this again. 

I essentially did the same thing you did but with DX11. I'm not sure how you got that to run with the GL implementation since as far as I know the Windows runtime uses DX11. 

I reached out to YYG to try and ask what data type the "texture pointer" is when using functions like sprite_get_texture. They basically told me I was shit out of luck since they can't help me with programming stuff I guess. I tried digging into the C# code with ILSpy but I'm worried I was pushing out of TOS boundaries by doing this. 

Currently I'm thinking about just making an unordered map on the CPP side and require the user to preload images with string names and use the names for the image functions. I'm open to any suggestions.

**Comment by noiamhippyman** [comment]
For now I'm just using a normal std::map and storing a ID3D11ShaderResourceView pointer. The only caveat here is we have to label the preloaded images and use a string for the image functions. But it's not bad considering things are working now and we're not recreating a buffer/surface/ShaderResourceView every single tick.
